language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: mindreeper2420@gmail.com
node_js:
  - '9'
  - '8'
  - '6'
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "mindreeper2420@gmail.com"
    - TRIGGER_REPO_SLUG: "mindreeper2420/fabric8-pattern.library.github.io"
    - TRIGGER_REPO_BRANCH: "master"
before_script:
  - npm install -g gulp-cli
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
